### ISSUE TITLE
Very cool

### ISSUE THREAD

**Issue by thehappydinoa** [amanszpapaya/MacPer#1]
Hey there,

This is really cool! I will make sure it add your tool to my readme as an alternative if you would be okay with that.

**Comment by amanszpapaya** [comment]
Hey,

It would be awesome, I'd be honored. And thanks again for the inspiration.

**Comment by thehappydinoa** [comment]
Okay! I just added it to my repo. I am really happy to see others continuing with this type of research. If there is ever anything I can help with or if you need someone to bounce ideas open my Twitter DMs are always open.
